package cms.academic.academicapp.service;

import java.util.List;

import cms.academic.academicapp.model.Discussion;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StudentDiscussionManager.java
//  @ Date : 5/10/2015
//  @ Author : 
//
//
import cms.academic.academicapp.model.EnrolledCourse;
import cms.academic.academicapp.model.User;

public interface StudentDiscussionService {
    public Integer addNewDiscussion(Discussion discussion) ;
    
    public Integer editDiscussion(Discussion discussion);
    
    public List<Discussion> courseDiscussions(EnrolledCourse enrolledCourse);
    
    public Integer removeDiscussion(Discussion discussion, User student);
    
    public Discussion viewDiscussion(Long discussionId);
}
